First I messed up th zuliprc-local file. 
Then I was unable to run followup.py successfully. 
At last I got stuck in subscription of streams.
